### ISSUE TITLE
Map filter

### ISSUE THREAD

**Issue by GogosKouk** [GiannisChatziaxiaris/Tour-Guide#35]
Filter the already existing map into showing only Points Of Interest such as:

Churches
Museums
Monuments
...

**Comment by GogosKouk** [comment]
git fetch origin
git checkout 35-map-filter

**Comment by GeorgeKouklidis** [comment]
Δεν μπόρεσε να ολοκληρωθεί μέχρι τα χρονικά πλαίσια
